
package Grecia;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class proj extends javax.swing.JFrame {

    /**
     * Creates new form proj
     */
    private List subjectList;
    private double ttlunits;
    private double ttlgrade;
    
    public proj() {
        initComponents();
        subjectList = new List(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        stuName = new javax.swing.JTextField();
        StuID = new javax.swing.JTextField();
        lblCode = new javax.swing.JTextField();
        lblDes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        unitsttl = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        gradesttl = new javax.swing.JLabel();
        derrekriangrecia = new javax.swing.JLabel();
        gradebox = new javax.swing.JComboBox<>();
        unitbox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GALAXY PROJ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Subject Code:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 150, -1));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Student ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, -1));

        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Name:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, -1));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("              ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 640, 90, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Units:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 150, -1));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 150, -1));

        stuName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuNameActionPerformed(evt);
            }
        });
        getContentPane().add(stuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 350, -1));

        StuID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuIDActionPerformed(evt);
            }
        });
        StuID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                StuIDKeyPressed(evt);
            }
        });
        getContentPane().add(StuID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 350, -1));

        lblCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCodeActionPerformed(evt);
            }
        });
        getContentPane().add(lblCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 350, -1));

        lblDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblDesActionPerformed(evt);
            }
        });
        getContentPane().add(lblDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 350, -1));

        tbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Subject Code", "Description", "Units", "Grades"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 830, 270));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Average Grade: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 150, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Grade: ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 150, -1));

        unitsttl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        unitsttl.setForeground(new java.awt.Color(255, 255, 255));
        unitsttl.setText("0.0");
        getContentPane().add(unitsttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 150, 30));

        add.setBackground(new java.awt.Color(51, 204, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setText("ADD SUBJECT");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 130, 30));

        Clear.setBackground(new java.awt.Color(255, 51, 51));
        Clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Clear.setText("CLEAR SUBJECT");
        Clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        getContentPane().add(Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, 130, 30));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("              ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 90, 30));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Units: ");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 590, 150, 30));

        gradesttl.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        gradesttl.setForeground(new java.awt.Color(255, 255, 255));
        gradesttl.setText("0.0");
        getContentPane().add(gradesttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 150, 30));
        getContentPane().add(derrekriangrecia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        gradebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "1.25", "1.5", "1.75", "2.0", "2.25", "2.50", "2.75", "3.00", "5.00" }));
        gradebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeboxActionPerformed(evt);
            }
        });
        getContentPane().add(gradebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 350, -1));

        unitbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.0", "2.0", "3.0", "4.0", "5.0", "6.0" }));
        getContentPane().add(unitbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 350, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Grecia/Your paragraph text (2).jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StuIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_StuIDActionPerformed

    private void StuIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StuIDKeyPressed
        // TODO add your handling code here:
        StuID.addKeyListener(new KeyAdapter(){
            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if(((c < '0')||(c > '9')) && (c != KeyEvent.VK_BACK_SPACE)){
                    e.consume();
                }
                
            }
        });
    }//GEN-LAST:event_StuIDKeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
         try {
                    String code = lblCode.getText(); 
                    String des = lblDes.getText();  
                    
                    if (code.isEmpty() || des.isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Code and Description must not be empty.");
                        return; 
                    }
                    double unitCount = Double.parseDouble(unitbox.getSelectedItem().toString());
                    double cbgrade = Double.parseDouble(gradebox.getSelectedItem().toString());
                        ttlunits += unitCount;
                        ttlgrade += unitCount * cbgrade;
                    
                    
                    
                    
                    SubList newSubject = new SubList(unitCount, cbgrade, "", "", code, des);
                    subjectList.addSubject(newSubject);

                    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
                    model.addRow(new Object[]{code, des, unitCount, cbgrade});  

                    lblCode.setText("");
                    lblDes.setText("");
                   
                    unitsttl.setText(""+ttlunits);
                    gradesttl.setText(String.format("%.4f", (ttlgrade / ttlunits)));

                } catch (NumberFormatException ex ) {
                    JOptionPane.showMessageDialog(null, "Please enter valid numbers for units and grades.");
                }
    }//GEN-LAST:event_addActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) tbl.getModel(); 
            model.setRowCount(0); 
            subjectList.clearSubjects();
            unitsttl.setText("0.0");
            gradesttl.setText("0.0");
            ttlunits = 0;
            ttlgrade = 0;
    }//GEN-LAST:event_ClearActionPerformed

    private void gradeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeboxActionPerformed

    private void stuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuNameActionPerformed

    private void lblCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCodeActionPerformed

    private void lblDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(proj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new proj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JTextField StuID;
    private javax.swing.JButton add;
    private javax.swing.JLabel derrekriangrecia;
    private javax.swing.JComboBox<String> gradebox;
    private javax.swing.JLabel gradesttl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblCode;
    private javax.swing.JTextField lblDes;
    private javax.swing.JTextField stuName;
    private javax.swing.JTable tbl;
    private javax.swing.JComboBox<String> unitbox;
    private javax.swing.JLabel unitsttl;
    // End of variables declaration//GEN-END:variables
}
